# Generated by Django 5.2.13 on 2026-05-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortmetricslkp',
            name='metric_id',
            field=models.IntegerField(db_comment='Primary key', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='machinelkp',
            name='machine_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
#        migrations.AlterModelTable(
#            name='objectiveclassification',
#            table='objective_classification',
#        ),
#        migrations.AlterModelTable(
#            name='taskclassification',
#            table='task_classification',
#        ),
    ]
