# Generated by Django 5.0.13 on 2025-04-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0002_alter_tasklkp_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklkp',
            name='task_name',
            field=models.CharField(blank=True, db_comment='Short meaningful name for the task', max_length=100, null=True),
        ),
    ]
