# Generated by Django 5.2.6 on 2025-12-05 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Report name for dropdown selection', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this report shows')),
                ('base_sql', models.TextField(help_text='Main SQL query without WHERE clause. Use {where_clause} placeholder. Example: SELECT * FROM table {where_clause}')),
                ('where_clauses', models.JSONField(blank=True, default=list, help_text='\n        JSON array of WHERE clause definitions. Example:\n        [\n            {\n                "field": "year",\n                "operator": "YEAR",\n                "parameter_name": "year",\n                "label": "Select Year",\n                "field_type": "select",\n                "options_query": "SELECT DISTINCT EXTRACT(YEAR FROM date_column) FROM table ORDER BY 1 DESC",\n                "default_value": "2024",\n                "required": true\n            },\n            {\n                "field": "supply",\n                "operator": "=",\n                "parameter_name": "supply",\n                "label": "Select Supply",\n                "field_type": "select",\n                "options_query": "SELECT DISTINCT supply FROM compartments ORDER BY supply",\n                "required": true\n            }\n        ]\n        ')),
                ('order_by', models.TextField(blank=True, help_text='ORDER BY clause. Example: region ASC, district DESC')),
                ('report_type', models.CharField(choices=[('polygon', 'Polygon Analysis'), ('cohort', 'Cohort Analysis'), ('treatment', 'Treatment Analysis'), ('operation', 'Operation Analysis'), ('custom', 'Custom Report')], default='custom', max_length=50)),
                ('export_formats', models.JSONField(default=list, help_text="JSON list of allowed export formats: ['excel', 'csv', 'pdf']")),
                ('columns', models.JSONField(blank=True, default=list, help_text='JSON array of column definitions for display. If empty, all columns will be shown.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='User groups that can run this report', to='auth.group')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SQL Report',
                'verbose_name_plural': 'SQL Reports',
                'ordering': ['name'],
            },
        ),
    ]
