# Generated by Django 5.2.6 on 2025-12-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlreport',
            name='export_formats',
            field=models.JSONField(default=list, help_text="JSON list of allowed export formats: ['excel', 'csv', 'pdf', 'shp']"),
        ),
    ]
