# Generated by Django 5.2.6 on 2026-02-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_alter_sqlreport_export_formats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textsearchfielddisplay',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='textsearchmodelconfig',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='SQLReport',
        ),
        migrations.DeleteModel(
            name='TextSearchFieldDisplay',
        ),
        migrations.DeleteModel(
            name='TextSearchModelConfig',
        ),
    ]
