# Generated by Django 5.2.6 on 2025-11-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_blocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignchttoply',
            name='status_current',
            field=models.BooleanField(default=True),
        ),
    ]
