# Generated by Django 5.2.6 on 2026-03-14 16:23

import django.core.files.storage
import django.db.models.deletion
import silrec.components.forest_blocks.models
import silrec.components.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_blocks', '0001_initial'),
        ('silrec', '0002_alter_auditlog_options_remove_auditlog_proposal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polygon',
            old_name='compartmen',
            new_name='compartment',
        ),
        migrations.RenameField(
            model_name='polygon',
            old_name='reason_clo',
            new_name='reason_closed',
        ),
        migrations.RenameField(
            model_name='polygonda',
            old_name='compartmen',
            new_name='compartment',
        ),
        migrations.RenameField(
            model_name='polygonda',
            old_name='reason_clo',
            new_name='reason_closed',
        ),
        migrations.AddField(
            model_name='operation',
            name='created_by',
            field=models.CharField(blank=True, db_comment='User who created the record', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_comment='Date and time when the record was created', null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='marked_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='operation',
            name='updated_by',
            field=models.CharField(blank=True, db_comment='User who last updated the record', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, db_comment='Date and time when the record was last updated', null=True),
        ),
        migrations.AddField(
            model_name='polygon',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='silrec.proposal'),
        ),
        migrations.AlterField(
            model_name='assignchttoply',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forest_blocks.cohort'),
        ),
        migrations.CreateModel(
            name='SurveyAssessmentDocument',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('survey', 'Survey Report'), ('assessment', 'Assessment Report'), ('image', 'Image'), ('map', 'Map'), ('other', 'Other Document')], default='other', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', silrec.components.main.models.SecureFileField(blank=True, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/ubuntu/projects/silrec/protected_media'), upload_to=silrec.components.forest_blocks.models.update_treatment_doc_filename)),
                ('file_url', models.URLField(blank=True, help_text='External URL for document', null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=20)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('marked_deleted', models.BooleanField(default=False)),
                ('uploaded_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='forest_blocks.treatment')),
            ],
            options={
                'db_table': 'survey_assessment_document',
                'db_table_comment': 'Stores documents, images, and URLs related to treatment surveys and assessments',
                'ordering': ['-document_date', '-created_on'],
            },
        ),
    ]
