# Generated by Django 5.2.10 on 2026-02-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forest_blocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polygon',
            old_name='compartmen',
            new_name='compartment',
        ),
        migrations.RenameField(
            model_name='polygon',
            old_name='reason_clo',
            new_name='reason_closed',
        ),
        migrations.RenameField(
            model_name='polygonda',
            old_name='compartmen',
            new_name='compartment',
        ),
        migrations.RenameField(
            model_name='polygonda',
            old_name='reason_clo',
            new_name='reason_closed',
        ),
    ]
