# Generated by Django 5.2.10 on 2026-02-27 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_blocks', '0002_rename_compartmen_polygon_compartment_and_more'),
        ('silrec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='silrec.proposal'),
        ),
        migrations.AlterField(
            model_name='assignchttoply',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forest_blocks.cohort'),
        ),
    ]
