# Generated by Django 5.2.13 on 2026-05-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_blocks', '0002_rename_compartmen_polygon_compartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='created_on',
            field=models.CharField(blank=True, db_comment='Date/time of creation of the polygon in the SILREC database', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='updated_on',
            field=models.CharField(blank=True, db_comment='date patch area was last changed', max_length=24, null=True),
        ),
    ]
