# Generated by Django 5.2.6 on 2025-11-10 20:30

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_blocks', '0002_assignchttoply_status_current'),
        ('lookups', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpCohort',
            fields=[
                ('cohort_id', models.AutoField(primary_key=True, serialize=False)),
                ('obj_code', models.CharField(db_comment='Silvicultural or management objective for the polygon', max_length=20)),
                ('op_id', models.IntegerField(blank=True, null=True)),
                ('op_date', models.DateTimeField(blank=True, db_comment='Date of creation of the operation boundary i.e. the date of photography, or other vector data capture method (GPS)', null=True)),
                ('pct_area', models.IntegerField(blank=True, db_comment='Percentage of stand/patch area occupied by the cohort allocated to or represented by this silvicultural objective', null=True)),
                ('year_last_cut', models.IntegerField(blank=True, db_comment='Year of last harvest of the cohort', null=True)),
                ('treatments', models.BooleanField(blank=True, db_comment='yes if treatments have been inserted for this cohort', null=True)),
                ('regen_date', models.DateTimeField(blank=True, db_comment='Date of majority regeneration', null=True)),
                ('regen_date2', models.DateTimeField(blank=True, db_comment='Date of secondary regeneration = the latest of any minority regeneration (e.g. infill planting)', null=True)),
                ('species', models.CharField(blank=True, db_comment='Dominant overstorey API species of cohort; refer to lookup table\n\n**This is usually calculated by the regen values function following regeneration-creating treatments, and has been manually updated in other cases.  \nConsideration required for systematic update following thinning changing the species composition', max_length=3, null=True)),
                ('regen_done', models.BooleanField(blank=True, db_comment='Yes if regeneration values  (date, species, method) have been calculated', null=True)),
                ('complete_date', models.DateTimeField(blank=True, db_comment='Date of completion of all activities directly required and intended for the silvic objective in this COHORT.\nExclude from consideration tasks that are long term, aspirational, or have been explicitly written off.', null=True)),
                ('resid_ba_m2ha', models.FloatField(blank=True, db_comment="Residual basal area of stand (average), m2/ha, including all overstorey trees following the implementation of all treatments entailed by the silvicultural objective.\n\nformerly 'ResidBA'", null=True)),
                ('target_ba_m2ha', models.FloatField(blank=True, null=True)),
                ('resid_spha', models.FloatField(blank=True, db_comment='Residual stocking of stand in stems per ha, averaged across stand, for all primary timber species.', null=True)),
                ('target_spha', models.IntegerField(blank=True, null=True)),
                ('site_quality', models.CharField(blank=True, db_comment='Mean cohort/polygon Site Quality class to 2 characters', max_length=6, null=True)),
                ('herbicide_app_spec', models.CharField(blank=True, db_comment='Intended herbicide application specification', max_length=50, null=True)),
                ('vrp_tot_area', models.FloatField(blank=True, db_comment='Vegetation retention patch total area (ha)', null=True)),
                ('comments', models.CharField(blank=True, db_comment='Any comments relevant to the setting of the objective for the patch or the residual stand parameters', max_length=250, null=True)),
                ('extra_info', models.BooleanField(blank=True, db_comment='Flag to show if additional attributes recorded or should be recorded in the cohort_xtra table', null=True)),
                ('created_on', models.DateTimeField(blank=True, db_comment='Date the record was created', null=True)),
                ('created_by', models.CharField(blank=True, db_comment='network user ID of person creating the record in the database', max_length=50, null=True)),
                ('updated_on', models.DateTimeField(blank=True, db_comment='date record was last changed', null=True)),
                ('updated_by', models.CharField(blank=True, db_comment='network user ID of person updating the record in the database', max_length=50, null=True)),
                ('stand', models.CharField(blank=True, max_length=10, null=True)),
                ('regen_method', models.ForeignKey(db_column='regen_method', db_comment="Method of Regeneration, consistent with FMIS codes; refer to lookup table\nProbably should default to value ' /' for not regenerated  **NEED TO MONITOR FOR ISSUES'", on_delete=django.db.models.deletion.CASCADE, to='lookups.regenerationmethodslkp')),
                ('vrp', models.ForeignKey(blank=True, db_comment='Number of vegetation retention patch', null=True, on_delete=django.db.models.deletion.CASCADE, to='forest_blocks.vegretpatch')),
            ],
            options={
                'db_table': 'tmp_cohort',
                'db_table_comment': "A cohort is characterised primarily by a silvicultural or management objective for a polygon, usually relating to a component of the dominant vegetation on the polygon.  The cohort has attribution related to the vegetation and institution of the silvicultural objective (which is usually some event).\nThis usually entails a suite of follow-up activities to ensure objective is achieved.\nA cohort is 'complete' when all activities prescribed for the institution of the silvicultural objective have been implemented or will not be implemented (no outstanding prescribed activities).\nA cohort is closed when superseded by an event creating a new management regime for the cohort; e.g. a thinning, wildfire or new management paradigm.  Cohort closure is a property of the assignment of the cohort to a polygon since a successive event may not (and typically doesn't) coincide geographically with the preceding event that instituted the cohort. \nIt follows that a cohort has a life that starts with some event, usually some silvicultural operation, or fire or change in the management paradigm; becomes 'complete' when required works are judged to have achieved intentions to an acceptable tolerance; and is closed when superseded by some other event.\nIf the cohort not closed, then it is the current silvicultural objective, and cohort characteristics represent the stand.",
            },
        ),
        migrations.CreateModel(
            name='TmpPolygon',
            fields=[
                ('polygon_id', models.AutoField(db_comment='Primary key', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_comment="Formerly 'PolyID'\nName of the polygon, usually descriptive of the administrative unit containing the polygon, e.g. code for forest block and compartment", max_length=10, null=True)),
                ('area_ha', models.FloatField(blank=True, db_comment='Area in ha of the polygon, as measured on flat/2D plane\nTrigger to calculate & populate ON UPDATE, ON CREATE', null=True)),
                ('created_on', models.DateTimeField(blank=True, db_comment='Date/time of creation of the polygon in the SILREC database', null=True)),
                ('created_by', models.CharField(blank=True, db_comment='user ID of person creating the polygon in the database', max_length=50, null=True)),
                ('updated_on', models.DateTimeField(blank=True, db_comment='date patch area was last changed', null=True)),
                ('updated_by', models.CharField(blank=True, db_comment='user ID of person updating the patch area in the database', max_length=50, null=True)),
                ('closed', models.DateField(blank=True, db_comment='Date when polygon is closed for activity; further work assigned to new, overlaying polygon\n\nALL open polygons (i.e. NOT CLOSED) should not overlap, i.e. planar enforcement', null=True)),
                ('reason_closed', models.CharField(blank=True, db_comment='Reason for closure of polygon, usually system related (data restructure), major perturbation resulting in destruction of multiple stands (e.g. wildfire), or new management regime (e.g. FMP24)', max_length=250, null=True)),
                ('zcoupeid', models.CharField(blank=True, db_column='zCoupeID', max_length=5, null=True)),
                ('zstandno', models.CharField(blank=True, db_column='zStandNo', max_length=5, null=True)),
                ('zmslink', models.FloatField(blank=True, db_column='zMSLink', null=True)),
                ('zfea_id', models.CharField(blank=True, db_comment='Operation Code defining or causing creation of the patch.\nWas Opcode. Now referred to as FEA ID on plan (DW)', max_length=7, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=28350)),
                ('compartment', models.ForeignKey(db_column='compartment', db_comment='foreign key to compartment and blocks table', on_delete=django.db.models.deletion.CASCADE, to='forest_blocks.compartments')),
                ('sp_code', models.ForeignKey(blank=True, db_column='sp_code', db_comment='Code for spatial precision of mapping or capture method\nforeign key to lookup table', null=True, on_delete=django.db.models.deletion.CASCADE, to='lookups.spatialprecisionlkp')),
            ],
            options={
                'db_table': 'tmp_polygon',
                'db_table_comment': "Geo-spatial object of non-zero area enclosing a portion of DBCA (or successor) estate.\n\nColumns in this table do and should only relate to the spatial occurrence of the polygon (DW).\nDelete comments below for PRD.\nArea column options\n1. Trigger to calculate and populate area of object when polygon created or updated.\n2. Drop the area column and recalculate area 'on the fly'\n\npreference for #1\n\nEasting and Northing have been dropped. (DW)\nPolygon_id was of type Long.  Changed to Integer. (DW)\nInteger is -32,768 to 32,768\nLong is -2,147,483,648 to 2,147,483,648\nQuestion if more than 32,768 polygons is likely?  (DW)",
            },
        ),
        migrations.CreateModel(
            name='TmpAssignChtToPly',
            fields=[
                ('cht2ply_id', models.AutoField(primary_key=True, serialize=False)),
                ('cohort_closed', models.DateField(blank=True, db_comment='Cohort is closed when stand is overwritten by new operation or some other disturbance creating a new stand.\n\nPolygon/area MUST always have an open (not closed) or current cohort.', null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('status_current', models.BooleanField(default=True)),
                ('op', models.ForeignKey(blank=True, db_comment='New cohort may be created by other than an operation therefore COLUMN IS NULLABLE', null=True, on_delete=django.db.models.deletion.CASCADE, to='forest_blocks.operation')),
                ('cohort', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forest_blocks.tmpcohort')),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forest_blocks.tmppolygon')),
            ],
            options={
                'db_table': 'tmp_assign_cht_to_ply',
                'db_table_comment': "As new operations or events create and subdivide polygons by creating new cohorts, cohorts apply to multiple polygons, as well as vice versa.\nSince a cohort may be closed for one polygon assignment, but open for another polygon assignment, the property of cohorts' closure is necessarily recorded in the assignment to the polygon.\nIt follows that cohort closure is most fully characterised as the date of the successive event and also a description of the nature of the cause of closure (e.g. fire, thin, ...).\nQuerying cohort closure may be part of investigations and analyses of relative frequency of types of closure events, or lifetime/return-time for different event types (e.g. thinning).\nThe property of closure relates primarily to the succeeding cohort, or the event creating the change.  Although this is often a new cohort, making the new cohort identification the closure attribute (e.g. foreign key to cohort) is inappropriate because:\n\n\t1. Complicates relationships with the assignment record already pointing to the preceding/current cohort.\n\t2. If there is a 'global' event (wildfire, polygon closure) wherein there is a universal cohort closure, and no immediate successive cohort for most assignments, it may be difficult to populate a key value.\n\nA date readily facilitates a query that will show a chronological cohort succession, but inter-row attribution and querying is difficult unless using an hierarchical query, but that query type requires a linking item.\nTherefore there are two choices to characterise cohort closure:\n\n\t1. a foreign key relationship to the succeeding cohort;\n\t2. a date and description of the nature of the event precipitating the closure of the cohort.  Likely the description is probably best implemented via a lookup table",
            },
        ),
    ]
