# Generated by Django 5.2.13 on 2026-05-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_blocks', '0002_rename_compartmen_polygon_compartment_and_more'),
    ]

    operations = [
#        migrations.AlterField(
#            model_name='cohort',
#            name='species',
#            field=models.CharField(blank=True, db_comment='Dominant overstorey API species of cohort; refer to lookup table\n\n**This is usually calculated by the regen values function following regeneration-creating treatments, and has been manually updated in other cases.  \nConsideration required for systematic update following thinning changing the species composition', max_length=5, null=True),
#        ),
        migrations.AlterField(
            model_name='treatmentxtra',
            name='api_species_assessed',
            field=models.CharField(blank=True, db_comment='Species mix (API) as determined by the assessment\nSHOULD LINK TO API SPECIES LOOKUP TABLE Done. (DW)', max_length=5, null=True),
        ),
    ]
