# Generated by Django 5.2.6 on 2025-11-16 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_blocks', '0003_tmpcohort_tmppolygon_tmpassignchttoply'),
        ('silrec', '0002_additionaldocumenttype_proposal_geojson_data_hist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='proposal',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='silrec.proposal'),
            preserve_default=False,
        ),
    ]
