# Generated by Django 5.2.6 on 2026-03-06 01:51

import django.core.files.storage
import silrec.components.forest_blocks.models
import silrec.components.main.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forest_blocks', '0004_surveyassessmentdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyassessmentdocument',
            name='file',
            field=silrec.components.main.models.SecureFileField(blank=True, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/ubuntu/projects/silrec/protected_media'), upload_to=silrec.components.forest_blocks.models.update_treatment_doc_filename),
        ),
    ]
