# Generated by Django 5.2.6 on 2025-11-16 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_blocks', '0004_polygon_proposal'),
        ('silrec', '0002_additionaldocumenttype_proposal_geojson_data_hist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='silrec.proposal'),
        ),
    ]
