# Generated by Django 5.2.6 on 2025-12-01 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_blocks', '0005_alter_polygon_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAssessmentDocument',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('survey', 'Survey Report'), ('assessment', 'Assessment Report'), ('photo', 'Photograph'), ('map', 'Map'), ('other', 'Other Document')], default='other', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='treatment_documents/%Y/%m/%d/')),
                ('file_url', models.URLField(blank=True, help_text='External URL for document', null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('reviewed', 'Reviewed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='forest_blocks.treatment')),
            ],
            options={
                'db_table': 'survey_assessment_document',
                'db_table_comment': 'Stores documents, images, and URLs related to treatment surveys and assessments',
                'ordering': ['-document_date', '-created_on'],
            },
        ),
    ]
