# Generated by Django 5.2.6 on 2026-03-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_blocks', '0005_alter_surveyassessmentdocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='created_by',
            field=models.CharField(blank=True, db_comment='User who created the record', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_comment='Date and time when the record was created', null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='marked_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='operation',
            name='updated_by',
            field=models.CharField(blank=True, db_comment='User who last updated the record', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, db_comment='Date and time when the record was last updated', null=True),
        ),
    ]
