# Generated by Django 5.2.6 on 2026-03-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_blocks', '0006_operation_created_by_operation_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='polygon_id',
            field=models.BigIntegerField(db_comment='Primary key', primary_key=True, serialize=False),
        ),
    ]
