# Generated by Django 5.2.6 on 2025-12-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_blocks', '0006_surveyassessmentdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyassessmentdocument',
            name='marked_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surveyassessmentdocument',
            name='document_type',
            field=models.CharField(choices=[('survey', 'Survey Report'), ('assessment', 'Assessment Report'), ('image', 'Image'), ('map', 'Map'), ('other', 'Other Document')], default='other', max_length=20),
        ),
    ]
