# Generated by Django 5.2.6 on 2026-03-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_blocks', '0007_alter_polygon_polygon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigncategorytotask',
            name='tsk2cat_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assignchttoply',
            name='cht2ply_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assignobjtoreport',
            name='obj2rpt_id',
            field=models.BigIntegerField(db_comment='primary key', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assigntasktoreport',
            name='tsk2rpt_id',
            field=models.BigIntegerField(db_comment='primary key', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='basweepversion',
            name='ba_version_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='batransect',
            name='ba_transect_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cell',
            name='cell_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clcomp2024polysclearedmga202050pl',
            name='gid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='cohort_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cohortresult',
            name='cr_id',
            field=models.BigIntegerField(db_comment='Primary key for the table', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cohortxtra',
            name='cohort_extra_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='combinedsilrec2023',
            name='gid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='combinedsilrec20232',
            name='gid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feaactivefmp25region',
            name='gid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='objectivecategory',
            name='obj_cat_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='objectivesubtype',
            name='type_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operation',
            name='op_id',
            field=models.BigIntegerField(db_comment='Unique identifier for each operation', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='polygonda',
            name='gid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='polygonminingunion',
            name='gid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_id',
            field=models.BigIntegerField(db_comment='Primary key', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reportcohort',
            name='report_id',
            field=models.BigIntegerField(db_comment='primary key', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reporttreatment',
            name='tsk_rpt_id',
            field=models.BigIntegerField(db_comment='primary key', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='silrecversion',
            name='version_id',
            field=models.BigIntegerField(db_comment="Primary key\nCorresponds to 'Build Number'", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='silrecversiontracking',
            name='tracking_id',
            field=models.BigIntegerField(db_comment='Primary key', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='silvicplaninput',
            name='silvplan_id',
            field=models.BigIntegerField(db_comment='Unique identifier for rows/items in the table\n(not part of input shape file)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='silviculturistcomment',
            name='s_comment_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='surveyassessmentdocument',
            name='document_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='tsk_cat_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_id',
            field=models.BigIntegerField(db_comment='Primary key identifying treatment\n(task implemented on polygon/cohort)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treatmentxtra',
            name='treatment_xtra_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vegretpatch',
            name='vrp_id',
            field=models.BigIntegerField(db_comment='Primary key', primary_key=True, serialize=False),
        ),
    ]
