# Generated by Django 5.2.6 on 2025-12-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_blocks', '0007_surveyassessmentdocument_marked_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='operation',
            table_comment="List of operations / coupes / FEA's. Provides a link back to planning units for analysis and reporting.\nOne row per FEA, each FEA can be linked to multiple cohorts.",
        ),
        migrations.AddField(
            model_name='operation',
            name='created_by',
            field=models.CharField(blank=True, db_comment='User who created the record', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_comment='Date and time when the record was created', null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='marked_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='operation',
            name='updated_by',
            field=models.CharField(blank=True, db_comment='User who last updated the record', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, db_comment='Date and time when the record was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='fea_id',
            field=models.CharField(blank=True, db_comment='Unique identifier for the FEA / OPERATION as determined by the planner', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='silvic_plan_doc',
            field=models.FileField(blank=True, db_comment='Silvic plan document (FINAL VERSION) providing the detailed silvicultural treatment', null=True, upload_to='silvic_plan_docs/'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='silvic_plan_map',
            field=models.FileField(blank=True, db_comment='Document (PDF) of a map of the silvics plan (FINAL VERSION)', null=True, upload_to='silvic_plan_maps/'),
        ),
        migrations.AlterField(
            model_name='surveyassessmentdocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=20),
        ),
    ]
