# Generated by Django 5.2.6 on 2025-12-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_blocks', '0008_alter_operation_table_comment_operation_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='silvic_plan_doc',
            field=models.BinaryField(blank=True, db_comment='Silvic plan document (FINAL VERSION) providing the detailed silvicultural tactics to be applied in the operation, may be .DOCX or PDF file.\n\nStore simply as URL to SharePoint location', null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='silvic_plan_map',
            field=models.BinaryField(blank=True, db_comment='Document (PDF) of a map of the silvics plan (FINAL VERSION)\n\nCorrect data type?\nStore simply as URL to SharePoint location', null=True),
        ),
    ]
