# Generated by Django 5.2.13 on 2026-05-08 10:41

import dirtyfields.dirtyfields
import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
import silrec.components.main.models
import silrec.components.proposals.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Additional Document Type',
                'db_table': 'additionaldocumenttype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Ecological_Thinning', 'Ecological Thinning'), ('Other', 'Other')], max_length=64, verbose_name='Application Type name')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('searchable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'applicationtype',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationsLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.TextField(blank=True, verbose_name='To')),
                ('fromm', models.CharField(blank=True, max_length=200, verbose_name='From')),
                ('cc', models.TextField(blank=True, verbose_name='cc')),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('mail', 'Mail'), ('person', 'In Person'), ('referral_complete', 'Referral Completed')], default='email', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Subject / Description')),
                ('text', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communicationslogentry',
            },
        ),
        migrations.CreateModel(
            name='FormValidationRule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text="Dotted model path, e.g. 'forest_blocks.Cohort'", max_length=100)),
                ('field_name', models.CharField(help_text='Field name on the model, e.g. obj_code, species', max_length=100)),
                ('field_label', models.CharField(blank=True, help_text='Human-readable label for error messages. Leave blank to use field_name.', max_length=200, null=True)),
                ('is_required', models.BooleanField(default=True, help_text='Check to make this field mandatory')),
                ('status_field', models.CharField(blank=True, help_text="Optional: model field that holds processing status (e.g. 'processing_status')", max_length=100, null=True)),
                ('status_values', models.CharField(blank=True, help_text="Optional: comma-separated status values when rule applies (e.g. 'draft,processing_shapefile'). Leave blank for all statuses.", max_length=500, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order in validation messages')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Form Validation Rule',
                'verbose_name_plural': 'Form Validation Rules',
                'db_table': 'form_validation_rule',
                'ordering': ['model_name', 'order', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='ProposalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'proposaltype',
            },
        ),
        migrations.CreateModel(
            name='SystemMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'System maintenance',
                'db_table': 'systemmaintenance',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_issuance_approval', models.JSONField(blank=True, null=True)),
                ('lodgement_number', models.CharField(blank=True, default='', max_length=9)),
                ('lodgement_date', models.DateTimeField(blank=True, null=True)),
                ('submitter', models.IntegerField(null=True)),
                ('processing_status', models.CharField(choices=[('draft', 'Draft'), ('processing_shapefile', 'Processing Shapefile'), ('amendment_required', 'Amendment Required'), ('with_assessor', 'With Assessor'), ('with_assessor_treatments', 'With Assessor (Treatments)'), ('with_assessor_tasks', 'With Assessor (Tasks)'), ('with_reviewer', 'With Reviewer'), ('review_completed', 'Review Completed'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('temp', 'Temporary')], default='draft', max_length=35, verbose_name='Processing Status')),
                ('prev_processing_status', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_transition_comment', models.TextField(blank=True, help_text='Change status comment', null=True)),
                ('shapefile_json', models.JSONField(blank=True, null=True, verbose_name='Source/Submitter (multi) polygon geometry')),
                ('geojson_data_hist', models.JSONField(blank=True, null=True, verbose_name='History Polygons that intersect Source Polygons')),
                ('geojson_data_processed', models.JSONField(blank=True, null=True, verbose_name='Source Polygon intersected with hist and split (multi) polygon geometry')),
                ('geojson_data_processed_iters', models.JSONField(blank=True, null=True, verbose_name='Source Polygon intersected with hist and split (multi) polygon geometry')),
                ('migrated', models.BooleanField(default=False)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silrec.applicationtype')),
                ('previous_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silrec.proposal')),
                ('proposal_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silrec.proposaltype')),
            ],
            options={
                'verbose_name': 'Proposal',
                'db_table': 'proposal',
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.CreateModel(
            name='ProposalAdditionalDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silrec.additionaldocumenttype')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_document_types', to='silrec.proposal')),
            ],
            options={
                'db_table': 'proposaladditionaldocumenttype',
            },
        ),
        migrations.CreateModel(
            name='ProposalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', silrec.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/ubuntu/projects/silrec/protected_media'), upload_to=silrec.components.proposals.models.update_proposal_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('can_hide', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='silrec.proposal')),
            ],
            options={
                'verbose_name': 'Application Document',
                'db_table': 'proposaldocument',
            },
        ),
        migrations.CreateModel(
            name='RequestMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_metrics', to='silrec.proposal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processing Log',
                'verbose_name_plural': 'Processing Logs',
                'db_table': 'requestmetrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(db_index=True, max_length=255)),
                ('record_id', models.PositiveIntegerField(db_index=True)),
                ('operation', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('iter_seq', models.PositiveIntegerField(verbose_name='Iteration')),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('request_metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='silrec.requestmetrics')),
            ],
            options={
                'db_table': 'auditlog',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SavepointRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.IntegerField(help_text='Iteration number in the processing run')),
                ('polygon_index', models.IntegerField(help_text='Index of the polygon being processed')),
                ('polygon_id', models.IntegerField(blank=True, help_text='ID of the polygon (if known)', null=True)),
                ('action', models.CharField(choices=[('create', 'Created'), ('commit', 'Committed'), ('rollback', 'Rolled Back')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_models', models.JSONField(default=dict, help_text='Counts of affected records per model')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('audit_logs', models.ManyToManyField(blank=True, related_name='savepoint_records', to='silrec.auditlog')),
            ],
            options={
                'verbose_name': 'Savepoint Record',
                'verbose_name_plural': 'Savepoint Records',
                'db_table': 'savepoint_record',
                'ordering': ['processing_run', 'iteration', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='savepoints',
            field=models.ManyToManyField(blank=True, related_name='audit_logs_for_savepoint', to='silrec.savepointrecord'),
        ),
        migrations.CreateModel(
            name='ShapefileAttributeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Exact name of the attribute column in the shapefile', max_length=255, verbose_name='Field Name')),
                ('display_name', models.CharField(blank=True, help_text='Human‑readable label (optional)', max_length=255, verbose_name='Display Name')),
                ('is_mandatory', models.BooleanField(default=False, help_text='If checked, the shapefile must contain this attribute', verbose_name='Mandatory')),
                ('is_reserved', models.BooleanField(default=False, help_text="If checked, the shapefile's polygon will NOT be merged", verbose_name='Is Reserved')),
                ('data_type', models.CharField(blank=True, choices=[(None, 'None (skip type check)'), ('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('date', 'Date')], default=None, help_text="Expected data type. Select 'None (skip type check)' to bypass.", max_length=50, null=True, verbose_name='Data Type')),
                ('target_db_field', models.CharField(blank=True, help_text="Optional mapping to a database field, e.g., 'silrec.forest_blocks.polygon.sp_code'", max_length=255, null=True, verbose_name='Target Database Field')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in admin/list views', verbose_name='Order')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapefile_attributes', to='silrec.applicationtype', verbose_name='Application Type')),
            ],
            options={
                'verbose_name': 'Shapefile Attribute Configuration',
                'verbose_name_plural': 'Shapefile Attribute Configurations',
                'db_table': 'shapefileattributeconfig',
                'ordering': ['application_type', 'order', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='ShapefileDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', silrec.components.main.models.SecureFileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/ubuntu/projects/silrec/protected_media'), upload_to=silrec.components.proposals.models.update_proposal_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('can_hide', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapefile_documents', to='silrec.proposal')),
            ],
            options={
                'db_table': 'shapefiledocument',
            },
        ),
        migrations.CreateModel(
            name='ShapefileProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField(help_text='Sliver threshold used for this processing run')),
                ('dump_file', models.FileField(blank=True, help_text='Path to the pg_dump file', max_length=512, null=True, upload_to='shapefile_processing/dumps/')),
                ('dump_filename', models.CharField(blank=True, help_text='Original filename of the pg_dump', max_length=255)),
                ('dump_size_bytes', models.BigIntegerField(blank=True, help_text='Size of the pg_dump file in bytes', null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('restored_at', models.DateTimeField(blank=True, help_text='When this dump was last restored via pg_restore', null=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapefile_processings', to='silrec.proposal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shapefile_processings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shapefile Processing (pg_dump)',
                'verbose_name_plural': 'Shapefile Processings (pg_dump)',
                'db_table': 'shapefile_processing',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ShapefileProcessingRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField(help_text='Sliver threshold used for this run')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_polygons', models.IntegerField(default=0, help_text='Total number of polygons to process')),
                ('processed_polygons', models.IntegerField(default=0, help_text='Number of polygons successfully processed')),
                ('failed_polygons', models.IntegerField(default=0, help_text='Number of polygons that failed')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_runs', to='silrec.proposal')),
                ('request_metrics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_run_metrics', to='silrec.requestmetrics')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shapefile Processing Run',
                'verbose_name_plural': 'Shapefile Processing Runs',
                'db_table': 'shapefile_processing_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='savepointrecord',
            name='processing_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savepoints', to='silrec.shapefileprocessingrun'),
        ),
        migrations.AddField(
            model_name='requestmetrics',
            name='processing_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics_for_run', to='silrec.shapefileprocessingrun'),
        ),
        migrations.CreateModel(
            name='SQLReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Report name for dropdown selection', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this report shows')),
                ('base_sql', models.TextField(help_text='Main SQL query without WHERE clause. Use {where_clause} placeholder. Example: SELECT * FROM table {where_clause}')),
                ('where_clauses', models.JSONField(blank=True, default=list, help_text='\n        JSON array of WHERE clause definitions. Example:\n        [\n            {\n                "field": "year",\n                "operator": "YEAR",\n                "parameter_name": "year",\n                "label": "Select Year",\n                "field_type": "select",\n                "options_query": "SELECT DISTINCT EXTRACT(YEAR FROM date_column) FROM table ORDER BY 1 DESC",\n                "default_value": "2024",\n                "required": true\n            },\n            {\n                "field": "supply",\n                "operator": "=",\n                "parameter_name": "supply",\n                "label": "Select Supply",\n                "field_type": "multiselect",\n                "options_query": "SELECT DISTINCT supply FROM compartments ORDER BY supply",\n                "required": true\n            }\n        ]\n        ')),
                ('order_by', models.TextField(blank=True, help_text='ORDER BY clause. Example: region ASC, district DESC')),
                ('report_type', models.CharField(choices=[('polygon', 'Polygon Analysis'), ('cohort', 'Chort Analysis'), ('treatment', 'Treatment Analysis'), ('operation', 'Operation Analysis'), ('custom', 'Custom Report')], default='custom', max_length=50)),
                ('export_formats', models.JSONField(default=list, help_text="JSON list of allowed export formats: ['excel', 'csv', 'pdf', 'shapefile']")),
                ('columns', models.JSONField(blank=True, default=list, help_text='JSON array of column definitions for display. If empty, all columns will be shown.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='User groups that can run this report', to='auth.group')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SQL Report',
                'verbose_name_plural': 'SQL Reports',
                'db_table': 'sqlreport',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(help_text='Auto-incremented version number for this template')),
                ('template_file', models.FileField(help_text='Upload a .docx file with Jinja2/docxtpl tags (e.g. {{ column_name }})', max_length=512, upload_to='report_templates/')),
                ('is_current', models.BooleanField(default=True, help_text='Only one template per report can be current at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='silrec.sqlreport')),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'db_table': 'report_template',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='TextSearchFieldDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True, verbose_name='Field Name')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_field_displays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Text Search Field Display',
                'verbose_name_plural': 'Text Search Field Displays',
                'db_table': 'textsearchfielddisplay',
                'ordering': ['order', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='TextSearchModelConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('proposal', 'Proposals'), ('polygon', 'Polygons'), ('cohort', 'Cohorts'), ('treatment', 'Treatments'), ('treatment_xtra', 'Treatment Extras'), ('survey_assessment_document', 'Survey Documents'), ('silviculturist_comment', 'Silviculturist Comments'), ('prescription', 'Prescriptions')], max_length=50, unique=True, verbose_name='Model Key')),
                ('model_name', models.CharField(help_text="Format: 'app_label.ModelName' (e.g., 'silrec.Proposal')", max_length=200, verbose_name='Django Model Path')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('search_fields', models.TextField(help_text='Comma-separated list of field names to search in this model', verbose_name='Search Fields')),
                ('date_field', models.CharField(default='created_on', help_text='Field name for creation date', max_length=100, verbose_name='Date Field')),
                ('id_field', models.CharField(default='id', help_text='Field name for the record ID', max_length=100, verbose_name='ID Field')),
                ('detail_fields', models.JSONField(default=list, help_text='List of field names to show in details column', verbose_name='Detail Fields')),
                ('url_pattern', models.CharField(help_text='URL pattern for detail view. Use {id} as placeholder for record ID', max_length=500, verbose_name='URL Pattern')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_search_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Text Search Model Configuration',
                'verbose_name_plural': 'Text Search Model Configurations',
                'db_table': 'textsearchmodelconfig',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='ProposalLogEntry',
            fields=[
                ('communicationslogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='silrec.communicationslogentry')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_logs', to='silrec.proposal')),
            ],
            options={
                'db_table': 'proposallogentry',
            },
            bases=('silrec.communicationslogentry',),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['table_name', 'record_id'], name='auditlog_table_n_073309_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shapefileattributeconfig',
            unique_together={('application_type', 'field_name')},
        ),
        migrations.AlterUniqueTogether(
            name='reporttemplate',
            unique_together={('report', 'version')},
        ),
    ]
