# Generated by Django 5.2.10 on 2026-02-26 08:31

import dirtyfields.dirtyfields
import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
import silrec.components.main.models
import silrec.components.proposals.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Additional Document Type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Ecological_Thinning', 'Ecological Thinning'), ('Other', 'Other')], max_length=64, verbose_name='Application Type name')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('searchable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProposalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'System maintenance',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_issuance_approval', models.JSONField(blank=True, null=True)),
                ('lodgement_number', models.CharField(blank=True, default='', max_length=9)),
                ('lodgement_date', models.DateTimeField(blank=True, null=True)),
                ('submitter', models.IntegerField(null=True)),
                ('processing_status', models.CharField(choices=[('draft', 'Draft'), ('amendment_required', 'Amendment Required'), ('with_assessor', 'With Assessor'), ('with_assessor_treatments', 'With Assessor (Treatments)'), ('with_assessor_tasks', 'With Assessor (Tasks)'), ('with_reviewer', 'With Reviewer'), ('review_Completed', 'Review Completed'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('temp', 'Temporary')], default='draft', max_length=35, verbose_name='Processing Status')),
                ('prev_processing_status', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('shapefile_json', models.JSONField(blank=True, null=True, verbose_name='Source/Submitter (multi) polygon geometry')),
                ('geojson_data_hist', models.JSONField(blank=True, null=True, verbose_name='History Polygons that intersect Source Polygons')),
                ('geojson_data_processed', models.JSONField(blank=True, null=True, verbose_name='Source Polygon intersected with hist and split (multi) polygon geometry')),
                ('geojson_data_processed_iters', models.JSONField(blank=True, null=True, verbose_name='Source Polygon intersected with hist and split (multi) polygon geometry')),
                ('migrated', models.BooleanField(default=False)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silrec.applicationtype')),
                ('previous_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silrec.proposal')),
                ('proposal_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silrec.proposaltype')),
            ],
            options={
                'verbose_name': 'Proposal',
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.CreateModel(
            name='ProposalAdditionalDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silrec.additionaldocumenttype')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_document_types', to='silrec.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', silrec.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/jawaidm/projects/silrec/protected_media'), upload_to=silrec.components.proposals.models.update_proposal_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('can_hide', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='silrec.proposal')),
            ],
            options={
                'verbose_name': 'Application Document',
            },
        ),
        migrations.CreateModel(
            name='ShapefileDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', silrec.components.main.models.SecureFileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/jawaidm/projects/silrec/protected_media'), upload_to=silrec.components.proposals.models.update_proposal_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('can_hide', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapefile_documents', to='silrec.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='SQLReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Report name for dropdown selection', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this report shows')),
                ('base_sql', models.TextField(help_text='Main SQL query without WHERE clause. Use {where_clause} placeholder. Example: SELECT * FROM table {where_clause}')),
                ('where_clauses', models.JSONField(blank=True, default=list, help_text='\n        JSON array of WHERE clause definitions. Example:\n        [\n            {\n                "field": "year",\n                "operator": "YEAR",\n                "parameter_name": "year",\n                "label": "Select Year",\n                "field_type": "select",\n                "options_query": "SELECT DISTINCT EXTRACT(YEAR FROM date_column) FROM table ORDER BY 1 DESC",\n                "default_value": "2024",\n                "required": true\n            },\n            {\n                "field": "supply",\n                "operator": "=",\n                "parameter_name": "supply",\n                "label": "Select Supply",\n                "field_type": "multiselect",\n                "options_query": "SELECT DISTINCT supply FROM compartments ORDER BY supply",\n                "required": true\n            }\n        ]\n        ')),
                ('order_by', models.TextField(blank=True, help_text='ORDER BY clause. Example: region ASC, district DESC')),
                ('report_type', models.CharField(choices=[('polygon', 'Polygon Analysis'), ('cohort', 'Chort Analysis'), ('treatment', 'Treatment Analysis'), ('operation', 'Operation Analysis'), ('custom', 'Custom Report')], default='custom', max_length=50)),
                ('export_formats', models.JSONField(default=list, help_text="JSON list of allowed export formats: ['excel', 'csv', 'pdf', 'shapefile']")),
                ('columns', models.JSONField(blank=True, default=list, help_text='JSON array of column definitions for display. If empty, all columns will be shown.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='User groups that can run this report', to='auth.group')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SQL Report',
                'verbose_name_plural': 'SQL Reports',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TextSearchFieldDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True, verbose_name='Field Name')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_field_displays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Text Search Field Display',
                'verbose_name_plural': 'Text Search Field Displays',
                'ordering': ['order', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='TextSearchModelConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('proposal', 'Proposals'), ('polygon', 'Polygons'), ('cohort', 'Cohorts'), ('treatment', 'Treatments'), ('treatment_xtra', 'Treatment Extras'), ('survey_assessment_document', 'Survey Documents'), ('silviculturist_comment', 'Silviculturist Comments'), ('prescription', 'Prescriptions')], max_length=50, unique=True, verbose_name='Model Key')),
                ('model_name', models.CharField(help_text="Format: 'app_label.ModelName' (e.g., 'silrec.Proposal')", max_length=200, verbose_name='Django Model Path')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('search_fields', models.TextField(help_text='Comma-separated list of field names to search in this model', verbose_name='Search Fields')),
                ('date_field', models.CharField(default='created_on', help_text='Field name for creation date', max_length=100, verbose_name='Date Field')),
                ('id_field', models.CharField(default='id', help_text='Field name for the record ID', max_length=100, verbose_name='ID Field')),
                ('detail_fields', models.JSONField(default=list, help_text='List of field names to show in details column', verbose_name='Detail Fields')),
                ('url_pattern', models.CharField(help_text='URL pattern for detail view. Use {id} as placeholder for record ID', max_length=500, verbose_name='URL Pattern')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_search_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Text Search Model Configuration',
                'verbose_name_plural': 'Text Search Model Configurations',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(db_index=True, max_length=255)),
                ('record_id', models.CharField(db_index=True, max_length=255)),
                ('operation', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='silrec.proposal')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['table_name', 'record_id'], name='silrec_audi_table_n_fec435_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShapefileAttributeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Exact name of the attribute column in the shapefile', max_length=255, verbose_name='Field Name')),
                ('display_name', models.CharField(blank=True, help_text='Human‑readable label (optional)', max_length=255, verbose_name='Display Name')),
                ('is_mandatory', models.BooleanField(default=False, help_text='If checked, the shapefile must contain this attribute', verbose_name='Mandatory')),
                ('is_reserved', models.BooleanField(default=False, help_text="If checked, the shapefile's polygon will NOT be merged", verbose_name='Is Reserved')),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('date', 'Date')], default='string', help_text='Expected data type (for future validation)', max_length=50, verbose_name='Data Type')),
                ('target_db_field', models.CharField(blank=True, help_text="Optional mapping to a database field, e.g., 'silrec.forest_blocks.polygon.sp_code'", max_length=255, null=True, verbose_name='Target Database Field')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in admin/list views', verbose_name='Order')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapefile_attributes', to='silrec.applicationtype', verbose_name='Application Type')),
            ],
            options={
                'verbose_name': 'Shapefile Attribute Configuration',
                'verbose_name_plural': 'Shapefile Attribute Configurations',
                'ordering': ['application_type', 'order', 'field_name'],
                'unique_together': {('application_type', 'field_name')},
            },
        ),
    ]
