# Generated by Django 5.2.6 on 2026-02-27 17:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silrec', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-start_time']},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='iter_seq',
            field=models.PositiveIntegerField(default=1, verbose_name='Iteration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='record_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.CreateModel(
            name='RequestMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_metrics', to='silrec.proposal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'requestmetrics',
                'ordering': ['-timestamp'], 'verbose_name': 'Processing Log', 'verbose_name_plural': 'Processing Logs',
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_metrics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='silrec.requestmetrics'),
            preserve_default=False,
        ),
    ]
