# Generated by Django 5.2.13 on 2026-05-07 11:19

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silrec', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationsLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.TextField(blank=True, verbose_name='To')),
                ('fromm', models.CharField(blank=True, max_length=200, verbose_name='From')),
                ('cc', models.TextField(blank=True, verbose_name='cc')),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('mail', 'Mail'), ('person', 'In Person'), ('referral_complete', 'Referral Completed')], default='email', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Subject / Description')),
                ('text', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communicationslogentry',
            },
        ),
        migrations.CreateModel(
            name='FormValidationRule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text="Dotted model path, e.g. 'forest_blocks.Cohort'", max_length=100)),
                ('field_name', models.CharField(help_text='Field name on the model, e.g. obj_code, species', max_length=100)),
                ('field_label', models.CharField(blank=True, help_text='Human-readable label for error messages. Leave blank to use field_name.', max_length=200, null=True)),
                ('is_required', models.BooleanField(default=True, help_text='Check to make this field mandatory')),
                ('status_field', models.CharField(blank=True, help_text="Optional: model field that holds processing status (e.g. 'processing_status')", max_length=100, null=True)),
                ('status_values', models.CharField(blank=True, help_text="Optional: comma-separated status values when rule applies (e.g. 'draft,processing_shapefile'). Leave blank for all statuses.", max_length=500, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order in validation messages')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Form Validation Rule',
                'verbose_name_plural': 'Form Validation Rules',
                'db_table': 'form_validation_rule',
                'ordering': ['model_name', 'order', 'field_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-start_time']},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='iter_seq',
            field=models.PositiveIntegerField(default=0, verbose_name='Iteration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='proposal',
            name='latest_transition_comment',
            field=models.TextField(blank=True, help_text='Change status comment', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='record_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing_shapefile', 'Processing Shapefile'), ('amendment_required', 'Amendment Required'), ('with_assessor', 'With Assessor'), ('with_assessor_treatments', 'With Assessor (Treatments)'), ('with_assessor_tasks', 'With Assessor (Tasks)'), ('with_reviewer', 'With Reviewer'), ('review_completed', 'Review Completed'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('temp', 'Temporary')], default='draft', max_length=35, verbose_name='Processing Status'),
        ),
        migrations.AlterField(
            model_name='shapefileattributeconfig',
            name='data_type',
            field=models.CharField(blank=True, choices=[(None, 'None (skip type check)'), ('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('date', 'Date')], default=None, help_text="Expected data type. Select 'None (skip type check)' to bypass.", max_length=50, null=True, verbose_name='Data Type'),
        ),
        migrations.AlterModelTable(
            name='applicationtype',
            table='applicationtype',
        ),
        migrations.AlterModelTable(
            name='systemmaintenance',
            table='systemmaintenance',
        ),
        migrations.CreateModel(
            name='RequestMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_metrics', to='silrec.proposal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processing Log',
                'verbose_name_plural': 'Processing Logs',
                'db_table': 'requestmetrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_metrics',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='silrec.requestmetrics'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SavepointRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.IntegerField(help_text='Iteration number in the processing run')),
                ('polygon_index', models.IntegerField(help_text='Index of the polygon being processed')),
                ('polygon_id', models.IntegerField(blank=True, help_text='ID of the polygon (if known)', null=True)),
                ('action', models.CharField(choices=[('create', 'Created'), ('commit', 'Committed'), ('rollback', 'Rolled Back')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_models', models.JSONField(default=dict, help_text='Counts of affected records per model')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('audit_logs', models.ManyToManyField(blank=True, related_name='savepoint_records', to='silrec.auditlog')),
            ],
            options={
                'verbose_name': 'Savepoint Record',
                'verbose_name_plural': 'Savepoint Records',
                'db_table': 'savepoint_record',
                'ordering': ['processing_run', 'iteration', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='savepoints',
            field=models.ManyToManyField(blank=True, related_name='audit_logs_for_savepoint', to='silrec.savepointrecord'),
        ),
        migrations.CreateModel(
            name='ShapefileProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField(help_text='Sliver threshold used for this processing run')),
                ('dump_file', models.FileField(blank=True, help_text='Path to the pg_dump file', max_length=512, null=True, upload_to='shapefile_processing/dumps/')),
                ('dump_filename', models.CharField(blank=True, help_text='Original filename of the pg_dump', max_length=255)),
                ('dump_size_bytes', models.BigIntegerField(blank=True, help_text='Size of the pg_dump file in bytes', null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('restored_at', models.DateTimeField(blank=True, help_text='When this dump was last restored via pg_restore', null=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapefile_processings', to='silrec.proposal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shapefile_processings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shapefile Processing (pg_dump)',
                'verbose_name_plural': 'Shapefile Processings (pg_dump)',
                'db_table': 'shapefile_processing',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ShapefileProcessingRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField(help_text='Sliver threshold used for this run')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_polygons', models.IntegerField(default=0, help_text='Total number of polygons to process')),
                ('processed_polygons', models.IntegerField(default=0, help_text='Number of polygons successfully processed')),
                ('failed_polygons', models.IntegerField(default=0, help_text='Number of polygons that failed')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_runs', to='silrec.proposal')),
                ('request_metrics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_run_metrics', to='silrec.requestmetrics')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shapefile Processing Run',
                'verbose_name_plural': 'Shapefile Processing Runs',
                'db_table': 'shapefile_processing_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='savepointrecord',
            name='processing_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savepoints', to='silrec.shapefileprocessingrun'),
        ),
        migrations.AddField(
            model_name='requestmetrics',
            name='processing_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics_for_run', to='silrec.shapefileprocessingrun'),
        ),
        migrations.CreateModel(
            name='ProposalLogEntry',
            fields=[
                ('communicationslogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='silrec.communicationslogentry')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_logs', to='silrec.proposal')),
            ],
            options={
                'db_table': 'proposallogentry',
            },
            bases=('silrec.communicationslogentry',),
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(help_text='Auto-incremented version number for this template')),
                ('template_file', models.FileField(help_text='Upload a .docx file with Jinja2/docxtpl tags (e.g. {{ column_name }})', max_length=512, upload_to='report_templates/')),
                ('is_current', models.BooleanField(default=True, help_text='Only one template per report can be current at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='silrec.sqlreport')),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'db_table': 'report_template',
                'ordering': ['-version'],
                'unique_together': {('report', 'version')},
            },
        ),
    ]
