# Generated by Django 5.2.5 on 2025-09-16 15:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silrec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Additional Document Type',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='proposal',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('amendment_required', 'Amendment Required'), ('with_assessor', 'With Assessor'), ('with_assessor_treatments', 'With Assessor (Treatments)'), ('with_assessor_tasks', 'With Assessor (Tasks)'), ('with_reviewer', 'With Reviewer'), ('review_Completed', 'Review Completed'), ('declined', 'Declined'), ('discarded', 'Discarded')], default='draft', max_length=35, verbose_name='Processing Status'),
        ),
        migrations.CreateModel(
            name='ProposalAdditionalDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silrec.additionaldocumenttype')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_document_types', to='silrec.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalGeometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('intersects', models.BooleanField(default=False)),
                ('drawn_by', models.IntegerField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, choices=[('proponent', 'Proponent'), ('assessor', 'Assessor')], default='proponent', max_length=255)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('locked', models.BooleanField(default=False)),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silrec.proposalgeometry')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposalgeometry', to='silrec.proposal')),
            ],
        ),
    ]
