# Generated by Django 5.2.6 on 2025-12-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silrec', '0002_additionaldocumenttype_proposal_geojson_data_hist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('amendment_required', 'Amendment Required'), ('with_assessor', 'With Assessor'), ('with_assessor_treatments', 'With Assessor (Treatments)'), ('with_assessor_tasks', 'With Assessor (Tasks)'), ('with_reviewer', 'With Reviewer'), ('review_Completed', 'Review Completed'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('temp', 'Temporary')], default='draft', max_length=35, verbose_name='Processing Status'),
        ),
    ]
