# Generated by Django 5.2.6 on 2026-03-16 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silrec', '0002_alter_auditlog_options_remove_auditlog_proposal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavepointRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.IntegerField(help_text='Iteration number in the processing run')),
                ('polygon_index', models.IntegerField(help_text='Index of the polygon being processed')),
                ('polygon_id', models.IntegerField(blank=True, help_text='ID of the polygon (if known)', null=True)),
                ('action', models.CharField(choices=[('create', 'Created'), ('commit', 'Committed'), ('rollback', 'Rolled Back')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_models', models.JSONField(default=dict, help_text='Counts of affected records per model')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('audit_logs', models.ManyToManyField(blank=True, related_name='savepoint_records', to='silrec.auditlog')),
            ],
            options={
                'verbose_name': 'Savepoint Record',
                'verbose_name_plural': 'Savepoint Records',
                'db_table': 'savepoint_record',
                'ordering': ['processing_run', 'iteration', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='savepoints',
            field=models.ManyToManyField(blank=True, related_name='audit_logs_for_savepoint', to='silrec.savepointrecord'),
        ),
        migrations.CreateModel(
            name='ShapefileProcessingRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField(help_text='Sliver threshold used for this run')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_polygons', models.IntegerField(default=0, help_text='Total number of polygons to process')),
                ('processed_polygons', models.IntegerField(default=0, help_text='Number of polygons successfully processed')),
                ('failed_polygons', models.IntegerField(default=0, help_text='Number of polygons that failed')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_runs', to='silrec.proposal')),
                ('request_metrics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_run_metrics', to='silrec.requestmetrics')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shapefile Processing Run',
                'verbose_name_plural': 'Shapefile Processing Runs',
                'db_table': 'shapefile_processing_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='savepointrecord',
            name='processing_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savepoints', to='silrec.shapefileprocessingrun'),
        ),
        migrations.AddField(
            model_name='requestmetrics',
            name='processing_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics_for_run', to='silrec.shapefileprocessingrun'),
        ),
    ]
