# Generated by Django 5.2.5 on 2025-09-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silrec', '0002_additionaldocumenttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='shapefile_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Source/Submitter (multi) polygon geometry'),
        ),
    ]
