# Generated by Django 5.2.6 on 2026-04-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silrec', '0003_savepointrecord_auditlog_savepoints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='latest_transition_comment',
            field=models.TextField(blank=True, help_text='Change status comment', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('amendment_required', 'Amendment Required'), ('with_assessor', 'With Assessor'), ('with_assessor_treatments', 'With Assessor (Treatments)'), ('with_assessor_tasks', 'With Assessor (Tasks)'), ('with_reviewer', 'With Reviewer'), ('review_completed', 'Review Completed'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('temp', 'Temporary')], default='draft', max_length=35, verbose_name='Processing Status'),
        ),
    ]
