# Generated by Django 5.2.6 on 2025-09-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silrec', '0003_proposal_shapefile_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='shp_processed_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Source Polygon intersected with hist and split (multi) polygon geometry'),
        ),
    ]
