# Generated by Django 5.2.13 on 2026-04-23 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silrec', '0004_add_latest_transition_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapefileProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField(help_text='Sliver threshold used for this processing run')),
                ('dump_file', models.FileField(blank=True, help_text='Path to the pg_dump file', max_length=512, null=True, upload_to='shapefile_processing/dumps/')),
                ('dump_filename', models.CharField(blank=True, help_text='Original filename of the pg_dump', max_length=255)),
                ('dump_size_bytes', models.BigIntegerField(blank=True, help_text='Size of the pg_dump file in bytes', null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapefile_processings', to='silrec.proposal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shapefile_processings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shapefile Processing (pg_dump)',
                'verbose_name_plural': 'Shapefile Processings (pg_dump)',
                'db_table': 'shapefile_processing',
                'ordering': ['-started_at'],
            },
        ),
    ]
