# Generated by Django 5.2.6 on 2025-09-30 14:17

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_blocks', '__first__'),
        ('silrec', '0004_proposal_shp_processed_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('area_ha', models.FloatField(blank=True, db_comment='Area in ha of the polygon', null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, db_comment='user ID', max_length=50, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, db_comment='user ID', max_length=50, null=True)),
                ('closed', models.DateField(blank=True, null=True)),
                ('reason_closed', models.CharField(blank=True, max_length=250, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=28350)),
                ('info', models.JSONField(blank=True, null=True)),
                ('polygon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='polygon', to='forest_blocks.polygon')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygonhistory', to='silrec.proposal')),
            ],
        ),
    ]
