# Generated by Django 5.2.6 on 2026-02-18 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silrec', '0004_basweeptransfer_basweepversion_batransecttransfer_and_more'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='tmppolygon',
#            name='proposal',
#            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tmp_polygons', to='silrec.proposal'),
#        ),
        migrations.AlterField(
            model_name='tmpassignchttoply',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silrec.tmpcohort'),
        ),
        migrations.AlterField(
            model_name='assignchttoply',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silrec.cohort'),
        ),
    ]
