# Generated by Django 5.2.6 on 2026-02-21 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('silrec', '0005_alter_tmpassignchttoply_cohort'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tmppolygon',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tmp_polygons', to='silrec.proposal'),
        ),
        migrations.CreateModel(
            name='SQLReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Report name for dropdown selection', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this report shows')),
                ('base_sql', models.TextField(help_text='Main SQL query without WHERE clause. Use {where_clause} placeholder. Example: SELECT * FROM table {where_clause}')),
                ('where_clauses', models.JSONField(blank=True, default=list, help_text='\n        JSON array of WHERE clause definitions. Example:\n        [\n            {\n                "field": "year",\n                "operator": "YEAR",\n                "parameter_name": "year",\n                "label": "Select Year",\n                "field_type": "select",\n                "options_query": "SELECT DISTINCT EXTRACT(YEAR FROM date_column) FROM table ORDER BY 1 DESC",\n                "default_value": "2024",\n                "required": true\n            },\n            {\n                "field": "supply",\n                "operator": "=",\n                "parameter_name": "supply",\n                "label": "Select Supply",\n                "field_type": "multiselect",\n                "options_query": "SELECT DISTINCT supply FROM compartments ORDER BY supply",\n                "required": true\n            }\n        ]\n        ')),
                ('order_by', models.TextField(blank=True, help_text='ORDER BY clause. Example: region ASC, district DESC')),
                ('report_type', models.CharField(choices=[('polygon', 'Polygon Analysis'), ('cohort', 'Chort Analysis'), ('treatment', 'Treatment Analysis'), ('operation', 'Operation Analysis'), ('custom', 'Custom Report')], default='custom', max_length=50)),
                ('export_formats', models.JSONField(default=list, help_text="JSON list of allowed export formats: ['excel', 'csv', 'pdf', 'shapefile']")),
                ('columns', models.JSONField(blank=True, default=list, help_text='JSON array of column definitions for display. If empty, all columns will be shown.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='User groups that can run this report', to='auth.group')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SQL Report',
                'verbose_name_plural': 'SQL Reports',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TextSearchFieldDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True, verbose_name='Field Name')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_field_displays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Text Search Field Display',
                'verbose_name_plural': 'Text Search Field Displays',
                'ordering': ['order', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='TextSearchModelConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('proposal', 'Proposals'), ('polygon', 'Polygons'), ('cohort', 'Cohorts'), ('treatment', 'Treatments'), ('treatment_xtra', 'Treatment Extras'), ('survey_assessment_document', 'Survey Documents'), ('silviculturist_comment', 'Silviculturist Comments'), ('prescription', 'Prescriptions')], max_length=50, unique=True, verbose_name='Model Key')),
                ('model_name', models.CharField(help_text="Format: 'app_label.ModelName' (e.g., 'silrec.Proposal')", max_length=200, verbose_name='Django Model Path')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('search_fields', models.TextField(help_text='Comma-separated list of field names to search in this model', verbose_name='Search Fields')),
                ('date_field', models.CharField(default='created_on', help_text='Field name for creation date', max_length=100, verbose_name='Date Field')),
                ('id_field', models.CharField(default='id', help_text='Field name for the record ID', max_length=100, verbose_name='ID Field')),
                ('detail_fields', models.JSONField(default=list, help_text='List of field names to show in details column', verbose_name='Detail Fields')),
                ('url_pattern', models.CharField(help_text='URL pattern for detail view. Use {id} as placeholder for record ID', max_length=500, verbose_name='URL Pattern')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_search_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Text Search Model Configuration',
                'verbose_name_plural': 'Text Search Model Configurations',
                'ordering': ['order', 'display_name'],
            },
        ),
    ]
