# Generated by Django 5.2.6 on 2025-09-30 14:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silrec', '0005_polygonhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygonhistory',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=28350),
        ),
    ]
