# Generated by Django 5.2.6 on 2026-02-18 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silrec', '0005_alter_tmpassignchttoply_cohort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignchttoply',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silrec.cohort'),
        ),
    ]
