# Generated by Django 5.2.13 on 2026-04-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silrec', '0005_shapefileprocessing'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapefileprocessing',
            name='restored_at',
            field=models.DateTimeField(blank=True, help_text='When this dump was last restored via pg_restore', null=True),
        ),
    ]
