# Generated by Django 5.2.13 on 2026-04-24 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silrec', '0006_shapefileprocessing_restored_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(help_text='Auto-incremented version number for this template')),
                ('template_file', models.FileField(help_text='Upload a .docx file with Jinja2/docxtpl tags (e.g. {{ column_name }})', max_length=512, upload_to='report_templates/')),
                ('is_current', models.BooleanField(default=True, help_text='Only one template per report can be current at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='silrec.sqlreport')),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'db_table': 'report_template',
                'ordering': ['-version'],
                'unique_together': {('report', 'version')},
            },
        ),
    ]
