# Generated by Django 5.2.6 on 2025-09-30 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silrec', '0006_alter_polygonhistory_geom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polygonhistory',
            old_name='polygon',
            new_name='polygon_src',
        ),
    ]
