# Generated by Django 5.2.6 on 2025-11-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silrec', '0007_rename_polygon_polygonhistory_polygon_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='geojson_data_hist',
            field=models.JSONField(blank=True, null=True, verbose_name='History Polygons that intersect Source Polygons'),
        ),
    ]
