# Generated by Django 5.2.6 on 2026-02-24 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silrec', '0007_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapefileAttributeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Exact name of the attribute column in the shapefile', max_length=255, verbose_name='Field Name')),
                ('display_name', models.CharField(blank=True, help_text='Human‑readable label (optional)', max_length=255, verbose_name='Display Name')),
                ('is_mandatory', models.BooleanField(default=False, help_text='If checked, the shapefile must contain this attribute', verbose_name='Mandatory')),
                ('is_reserved', models.BooleanField(default=False, help_text="If checked, the shapefile's polygon will NOT be merged", verbose_name='Is Reserved')),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('date', 'Date')], default='string', help_text='Expected data type (for future validation)', max_length=50, verbose_name='Data Type')),
                ('target_db_field', models.CharField(blank=True, help_text="Optional mapping to a database field, e.g., 'silrec.forest_blocks.polygon.sp_code'", max_length=255, null=True, verbose_name='Target Database Field')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in admin/list views', verbose_name='Order')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapefile_attributes', to='silrec.applicationtype', verbose_name='Application Type')),
            ],
            options={
                'verbose_name': 'Shapefile Attribute Configuration',
                'verbose_name_plural': 'Shapefile Attribute Configurations',
                'ordering': ['application_type', 'order', 'field_name'],
                'unique_together': {('application_type', 'field_name')},
            },
        ),
    ]
