# Generated by Django 5.2.13 on 2026-04-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silrec', '0009_alter_proposal_processing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormValidationRule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text="Dotted model path, e.g. 'forest_blocks.Cohort'", max_length=100)),
                ('field_name', models.CharField(help_text='Field name on the model, e.g. obj_code, species', max_length=100)),
                ('field_label', models.CharField(blank=True, help_text='Human-readable label for error messages. Leave blank to use field_name.', max_length=200, null=True)),
                ('is_required', models.BooleanField(default=True, help_text='Check to make this field mandatory')),
                ('status_field', models.CharField(blank=True, help_text="Optional: model field that holds processing status (e.g. 'processing_status')", max_length=100, null=True)),
                ('status_values', models.CharField(blank=True, help_text="Optional: comma-separated status values when rule applies (e.g. 'draft,processing_shapefile'). Leave blank for all statuses.", max_length=500, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order in validation messages')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Form Validation Rule',
                'verbose_name_plural': 'Form Validation Rules',
                'db_table': 'form_validation_rule',
                'ordering': ['model_name', 'order', 'field_name'],
            },
        ),
    ]
